# Grafana数据源自动配置
# 用于自动添加VictoriaMetrics数据源

apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://vmselect:8481/select/0/prometheus
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 30s
