# vmagent配置文件
# 用于从Prometheus兼容的端点采集数据

global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  # 示例：从Prometheus端点采集数据
  # 实际使用中，T-BOX数据通过MQTT桥接器直接写入VictoriaMetrics
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['vmselect:8481']
